### PR TITLE
Invoke-VCFCommand

### PR DESCRIPTION
**Pull request by giulianoberteo**
This PR include two new functions:
**Resolve-PSModule**

**Invoke-VCFCommand** in this initial version supports the following SoS options:
- general-health
- compute-health
- ntp-health
- password-health
- get-vcf-summary
- get-inventory-info
- get-host-ips
- get-vcf-services-summary

### CODE REVIEW

**Comment by PowerVCF** [comment]
There is a conflict in this branch. Will review tomorrow morning as out of time today

**Comment by giulianoberteo** [comment]
Strange, when I created the PR there was no conflict, talk tomorrow

**Comment by giulianoberteo** [comment]
Strange, there was no conflict yesterday. maybe another PR was merged before. checking tomoroww

**Comment by giulianoberteo** [comment]
ok I see what's happened. 
in PR #42 I mistakenly did a commit where I added Invoke-VCFCommand, which was meant for #41

The only commit needed in #42 is the one that return $response

**Pull request closed without merging**
