### PR TITLE
Fix indent using Visual Code Formatter

### PR DESCRIPTION
**Pull request by alagoutte**
i use 2 spaces indent (may be switch to 4 ?)

add also add .vscode settings

### CODE REVIEW

**Comment by alagoutte** [comment]
rebase my patches with last change...

**Comment by tsugliani** [comment]
Oh yes, I was waiting for this, it's driving my OCD nuts  ! :-) 👍

**Comment by GaryJBlake** [comment]
Rejecting this Pull Request, we have made significant changes to support VCF 4.0 and this Pull Request now has many conflicts

**Comment by alagoutte** [comment]
Hi,

i can rebase my change...

**Pull request closed without merging**
